### ISSUE TITLE
Support scaling to zerp

### ISSUE THREAD

**Issue by jjhuff** [jthomperoo/custom-pod-autoscaler#109]
This code seems to be preventing me from scaling a deployment to zero replicas:
https://github.com/jthomperoo/custom-pod-autoscaler/blob/7b1d427baac5db9d01191453f2728bb9f552c9cd/scale/scale.go#L112

My use case is a queue-based processing system with a bunch of GPUs, so scale to zero is rather important (and also why I can't use the build in HorizontalPodAutoscaler)

**Comment by jthomperoo** [comment]
I think this is a copy of #108.

**Comment by jjhuff** [comment]
Yeah, GH issues this morning
