### ISSUE TITLE
Support  operators (CRD based custom controllers)

### ISSUE THREAD

**Issue by igorshevach** [jthomperoo/custom-pod-autoscaler#159]
**Is your feature request related to a problem? Please describe.**
Today CPA does not work with operators.  instead, it keeps logging error "Error while autoscaling: failed to get managed resource: the server could not find the requested resource"

**Describe the solution you'd like**
Do what kubernetes HPA does; instead of querying replicas from a resource like replcationcontroller etc. retrieve scale object
(have a look at scaleForResourceMappings) 

**Describe alternatives you've considered**
see above

**Comment by jthomperoo** [comment]
This is now available in version [v2.5.0](https://github.com/jthomperoo/custom-pod-autoscaler/releases/tag/v2.5.0).
