### ISSUE TITLE
[question] Does this repo only support kubernetes metrics?

### ISSUE THREAD

**Issue by Jeffwan** [jthomperoo/custom-pod-autoscaler#198]
I am curious whether this custom pod autoscaler framework support fetching metrics from pod directly instead of using kubernetes metrics?

**Comment by jthomperoo** [comment]
Hi @Jeffwan, yes Custom Pod Autoscalers can fetch metrics directly from pods, see this example to see how to do that:

https://github.com/jthomperoo/custom-pod-autoscaler/tree/5d39741bd6990c5268dc46dddcac2e7e8c0067ba/example/simple-pod-metrics-python

In the `metric.py` script it grabs the pod IP and uses that to send a request to an arbitrary `/metrics` endpoint exposed by the pod:

https://github.com/jthomperoo/custom-pod-autoscaler/blob/5d39741bd6990c5268dc46dddcac2e7e8c0067ba/example/simple-pod-metrics-python/metric.py#L38-L55

**Comment by jthomperoo** [comment]
If my response able hasn't answered your question fully just re-open this issue with a comment explaining why.
Thanks!

**Comment by Jeffwan** [comment]
@jthomperoo Thanks! I read the code and understand how it works now. kuberneresMetrics is actually additional metrics cpa can help feed into `metric` component, the primary focus could be per service or per pod metric scraping
